name: Run k6 tests

on: [push, pull_request]

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install k6
        run: sudo apt-get update && sudo apt-get install -y k6

      - name: Run k6 tests
        run: k6 run browser-test.js

      - name: Upload k6 results
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: ignore
