name: Run k6 tests

on: [push, pull_request]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup k6 with browser support
        uses: grafana/setup-k6-action@v1
        with:
          browser: true

      - name: Run k6 tests
        uses: grafana/run-k6-action@v1
        with:
          path: |
            browser-script.js

      - name: Upload k6 screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: ignore
